app:
  nombre: "etl_entregas"
  entorno: "develop"

input:
  ruta_raw: "data/raw/global_mobility_data_entrega_productos.csv"

output:
  ruta_silver: "data/silver"
  ruta_processed: "data/processed"
  formato: "parquet"
  modo_escritura: "overwrite"

filtros:
  fecha_inicio: "2025-01-01"
  fecha_fin: "2025-06-30"
  pais: null

reglas_negocio:
  conversion_cs_a_st: 20
  entregas_rutina: ["ZPRE", "ZVE1"]
  entregas_bonificacion: ["Z04", "Z05"]

calidad_datos:
  unidades_validas: ["CS", "ST"]
  tipos_entrega_validos: ["ZPRE", "ZVE1", "Z04", "Z05"]
